//import com.sforce.soap.metadata.*;

/**
* Sample that logs in and creates a custom object through the metadata api
*/
public class CRUDSample {
    //MetadataService.MetadataPort service = new MetadataService.MetadataPort();  
    /*service.SessionHeader = new MetadataService.SessionHeader_element();
    service.SessionHeader.sessionId = UserInfo.getSessionId();
    
    List<MetadataService.Metadata> fields = new List<MetadataService.Metadata>();
    MetadataService.CustomObject  customobject = new MetadataService.CustomObject();
    customobject.fullName = 'custom_create__c';
    customobject.label = 'Custom created object';
    customobject.pluralLabel = 'Custom created objects';
    customObject.nameField = new MetadataService.CustomField();
    customobject.nameField.type_x = 'Text';
    customobject.nameField.label = 'Custom created field';
    customobject.deploymentStatus = 'Deployed';
    customObject.sharingModel = 'ReadWrite';
    fields.add(customobject);
    
    MetadataService.AsyncResult[] results = service.create(fields);*/
}