public class WrapperComparator implements Comparable{
    public class Wrapper1{
        public string Name = 'Bibhu';
    }
    public class Wrapper2{
        public string Name = 'Prashant';
    }
    public integer compareTo(object objToCompare){
        return 0;
    }
    public integer compareTo(object objToCompare1, object objToCompare2){
        if(objToCompare1 == objToCompare2){
            return 0;
        }
        
        return 0;
    }

}